# coding: utf-8

"""
    Lens Control API

    API For controlling the lens on Blackmagic Design products  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2001(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'focal_length': 'FocalLength',
        'normalised': 'Normalised'
    }

    attribute_map = {
        'focal_length': 'focalLength',
        'normalised': 'normalised'
    }

    def __init__(self, focal_length=None, normalised=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger"""  # noqa: E501
        self._focal_length = None
        self._normalised = None
        self.discriminator = None
        if focal_length is not None:
            self.focal_length = focal_length
        if normalised is not None:
            self.normalised = normalised

    @property
    def focal_length(self):
        """Gets the focal_length of this InlineResponse2001.  # noqa: E501


        :return: The focal_length of this InlineResponse2001.  # noqa: E501
        :rtype: FocalLength
        """
        return self._focal_length

    @focal_length.setter
    def focal_length(self, focal_length):
        """Sets the focal_length of this InlineResponse2001.


        :param focal_length: The focal_length of this InlineResponse2001.  # noqa: E501
        :type: FocalLength
        """

        self._focal_length = focal_length

    @property
    def normalised(self):
        """Gets the normalised of this InlineResponse2001.  # noqa: E501


        :return: The normalised of this InlineResponse2001.  # noqa: E501
        :rtype: Normalised
        """
        return self._normalised

    @normalised.setter
    def normalised(self, normalised):
        """Sets the normalised of this InlineResponse2001.


        :param normalised: The normalised of this InlineResponse2001.  # noqa: E501
        :type: Normalised
        """

        self._normalised = normalised

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2001, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2001):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
