# coding: utf-8

"""
    System Control API

    API for controlling the System Modes on Blackmagic Design products.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CodecFormat(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'codec': 'str',
        'container': 'str'
    }

    attribute_map = {
        'codec': 'codec',
        'container': 'container'
    }

    def __init__(self, codec=None, container=None):  # noqa: E501
        """CodecFormat - a model defined in Swagger"""  # noqa: E501
        self._codec = None
        self._container = None
        self.discriminator = None
        if codec is not None:
            self.codec = codec
        if container is not None:
            self.container = container

    @property
    def codec(self):
        """Gets the codec of this CodecFormat.  # noqa: E501

        Currently selected codec  # noqa: E501

        :return: The codec of this CodecFormat.  # noqa: E501
        :rtype: str
        """
        return self._codec

    @codec.setter
    def codec(self, codec):
        """Sets the codec of this CodecFormat.

        Currently selected codec  # noqa: E501

        :param codec: The codec of this CodecFormat.  # noqa: E501
        :type: str
        """

        self._codec = codec

    @property
    def container(self):
        """Gets the container of this CodecFormat.  # noqa: E501

        Multimedia container format  # noqa: E501

        :return: The container of this CodecFormat.  # noqa: E501
        :rtype: str
        """
        return self._container

    @container.setter
    def container(self, container):
        """Sets the container of this CodecFormat.

        Multimedia container format  # noqa: E501

        :param container: The container of this CodecFormat.  # noqa: E501
        :type: str
        """

        self._container = container

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CodecFormat, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CodecFormat):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
