# coding: utf-8

"""
    System Control API

    API for controlling the System Modes on Blackmagic Design products.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SystemResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'codec_format': 'CodecFormat',
        'video_format': 'GetVideoFormat'
    }

    attribute_map = {
        'codec_format': 'codecFormat',
        'video_format': 'videoFormat'
    }

    def __init__(self, codec_format=None, video_format=None):  # noqa: E501
        """SystemResponse - a model defined in Swagger"""  # noqa: E501
        self._codec_format = None
        self._video_format = None
        self.discriminator = None
        if codec_format is not None:
            self.codec_format = codec_format
        if video_format is not None:
            self.video_format = video_format

    @property
    def codec_format(self):
        """Gets the codec_format of this SystemResponse.  # noqa: E501


        :return: The codec_format of this SystemResponse.  # noqa: E501
        :rtype: CodecFormat
        """
        return self._codec_format

    @codec_format.setter
    def codec_format(self, codec_format):
        """Sets the codec_format of this SystemResponse.


        :param codec_format: The codec_format of this SystemResponse.  # noqa: E501
        :type: CodecFormat
        """

        self._codec_format = codec_format

    @property
    def video_format(self):
        """Gets the video_format of this SystemResponse.  # noqa: E501


        :return: The video_format of this SystemResponse.  # noqa: E501
        :rtype: GetVideoFormat
        """
        return self._video_format

    @video_format.setter
    def video_format(self, video_format):
        """Sets the video_format of this SystemResponse.


        :param video_format: The video_format of this SystemResponse.  # noqa: E501
        :type: GetVideoFormat
        """

        self._video_format = video_format

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SystemResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
