# coding: utf-8

"""
    System Control API

    API for controlling the System Modes on Blackmagic Design products.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class VideoFormat(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'frame_rate': 'FrameRate',
        'height': 'float',
        'width': 'float',
        'interlaced': 'bool'
    }

    attribute_map = {
        'frame_rate': 'frameRate',
        'height': 'height',
        'width': 'width',
        'interlaced': 'interlaced'
    }

    def __init__(self, frame_rate=None, height=None, width=None, interlaced=None):  # noqa: E501
        """VideoFormat - a model defined in Swagger"""  # noqa: E501
        self._frame_rate = None
        self._height = None
        self._width = None
        self._interlaced = None
        self.discriminator = None
        if frame_rate is not None:
            self.frame_rate = frame_rate
        if height is not None:
            self.height = height
        if width is not None:
            self.width = width
        if interlaced is not None:
            self.interlaced = interlaced

    @property
    def frame_rate(self):
        """Gets the frame_rate of this VideoFormat.  # noqa: E501


        :return: The frame_rate of this VideoFormat.  # noqa: E501
        :rtype: FrameRate
        """
        return self._frame_rate

    @frame_rate.setter
    def frame_rate(self, frame_rate):
        """Sets the frame_rate of this VideoFormat.


        :param frame_rate: The frame_rate of this VideoFormat.  # noqa: E501
        :type: FrameRate
        """

        self._frame_rate = frame_rate

    @property
    def height(self):
        """Gets the height of this VideoFormat.  # noqa: E501

        Height dimension of video format  # noqa: E501

        :return: The height of this VideoFormat.  # noqa: E501
        :rtype: float
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this VideoFormat.

        Height dimension of video format  # noqa: E501

        :param height: The height of this VideoFormat.  # noqa: E501
        :type: float
        """

        self._height = height

    @property
    def width(self):
        """Gets the width of this VideoFormat.  # noqa: E501

        Width dimension of video format  # noqa: E501

        :return: The width of this VideoFormat.  # noqa: E501
        :rtype: float
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this VideoFormat.

        Width dimension of video format  # noqa: E501

        :param width: The width of this VideoFormat.  # noqa: E501
        :type: float
        """

        self._width = width

    @property
    def interlaced(self):
        """Gets the interlaced of this VideoFormat.  # noqa: E501

        Is the display format interlaced?  # noqa: E501

        :return: The interlaced of this VideoFormat.  # noqa: E501
        :rtype: bool
        """
        return self._interlaced

    @interlaced.setter
    def interlaced(self, interlaced):
        """Sets the interlaced of this VideoFormat.

        Is the display format interlaced?  # noqa: E501

        :param interlaced: The interlaced of this VideoFormat.  # noqa: E501
        :type: bool
        """

        self._interlaced = interlaced

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VideoFormat, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VideoFormat):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
