# coding: utf-8

"""
    Color Correction Control API

    API For controlling the color correction on Blackmagic Design products based on DaVinci Resolve Color Corrector  # noqa: E501

    OpenAPI spec version: 0.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Color(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hue': 'float',
        'saturation': 'float'
    }

    attribute_map = {
        'hue': 'hue',
        'saturation': 'saturation'
    }

    def __init__(self, hue=0.0, saturation=1.0):  # noqa: E501
        """Color - a model defined in Swagger"""  # noqa: E501
        self._hue = None
        self._saturation = None
        self.discriminator = None
        if hue is not None:
            self.hue = hue
        if saturation is not None:
            self.saturation = saturation

    @property
    def hue(self):
        """Gets the hue of this Color.  # noqa: E501


        :return: The hue of this Color.  # noqa: E501
        :rtype: float
        """
        return self._hue

    @hue.setter
    def hue(self, hue):
        """Sets the hue of this Color.


        :param hue: The hue of this Color.  # noqa: E501
        :type: float
        """

        self._hue = hue

    @property
    def saturation(self):
        """Gets the saturation of this Color.  # noqa: E501


        :return: The saturation of this Color.  # noqa: E501
        :rtype: float
        """
        return self._saturation

    @saturation.setter
    def saturation(self, saturation):
        """Sets the saturation of this Color.


        :param saturation: The saturation of this Color.  # noqa: E501
        :type: float
        """

        self._saturation = saturation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Color, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Color):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
