# coding: utf-8

"""
    Color Correction Control API

    API For controlling the color correction on Blackmagic Design products based on DaVinci Resolve Color Corrector  # noqa: E501

    OpenAPI spec version: 0.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LumaContribution(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'luma_contribution': 'float'
    }

    attribute_map = {
        'luma_contribution': 'lumaContribution'
    }

    def __init__(self, luma_contribution=1.0):  # noqa: E501
        """LumaContribution - a model defined in Swagger"""  # noqa: E501
        self._luma_contribution = None
        self.discriminator = None
        if luma_contribution is not None:
            self.luma_contribution = luma_contribution

    @property
    def luma_contribution(self):
        """Gets the luma_contribution of this LumaContribution.  # noqa: E501


        :return: The luma_contribution of this LumaContribution.  # noqa: E501
        :rtype: float
        """
        return self._luma_contribution

    @luma_contribution.setter
    def luma_contribution(self, luma_contribution):
        """Sets the luma_contribution of this LumaContribution.


        :param luma_contribution: The luma_contribution of this LumaContribution.  # noqa: E501
        :type: float
        """

        self._luma_contribution = luma_contribution

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LumaContribution, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LumaContribution):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
