# coding: utf-8

"""
    Timeline Control API

    API for controlling playback timeline.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TimelineClips(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'clip_unique_id': 'int',
        'frame_count': 'int'
    }

    attribute_map = {
        'clip_unique_id': 'clipUniqueId',
        'frame_count': 'frameCount'
    }

    def __init__(self, clip_unique_id=None, frame_count=None):  # noqa: E501
        """TimelineClips - a model defined in Swagger"""  # noqa: E501
        self._clip_unique_id = None
        self._frame_count = None
        self.discriminator = None
        if clip_unique_id is not None:
            self.clip_unique_id = clip_unique_id
        if frame_count is not None:
            self.frame_count = frame_count

    @property
    def clip_unique_id(self):
        """Gets the clip_unique_id of this TimelineClips.  # noqa: E501

        Unique ID used to identify this clip  # noqa: E501

        :return: The clip_unique_id of this TimelineClips.  # noqa: E501
        :rtype: int
        """
        return self._clip_unique_id

    @clip_unique_id.setter
    def clip_unique_id(self, clip_unique_id):
        """Sets the clip_unique_id of this TimelineClips.

        Unique ID used to identify this clip  # noqa: E501

        :param clip_unique_id: The clip_unique_id of this TimelineClips.  # noqa: E501
        :type: int
        """

        self._clip_unique_id = clip_unique_id

    @property
    def frame_count(self):
        """Gets the frame_count of this TimelineClips.  # noqa: E501

        Number of frames in this clip on the timeline  # noqa: E501

        :return: The frame_count of this TimelineClips.  # noqa: E501
        :rtype: int
        """
        return self._frame_count

    @frame_count.setter
    def frame_count(self, frame_count):
        """Sets the frame_count of this TimelineClips.

        Number of frames in this clip on the timeline  # noqa: E501

        :param frame_count: The frame_count of this TimelineClips.  # noqa: E501
        :type: int
        """

        self._frame_count = frame_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TimelineClips, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TimelineClips):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
