# coding: utf-8

"""
    Media Control API

    API for controlling media devices in Blackmagic Design products.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DeviceNameDoformatBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'FormatKey',
        'filesystem': 'str',
        'volume': 'str'
    }

    attribute_map = {
        'key': 'key',
        'filesystem': 'filesystem',
        'volume': 'volume'
    }

    def __init__(self, key=None, filesystem=None, volume=None):  # noqa: E501
        """DeviceNameDoformatBody - a model defined in Swagger"""  # noqa: E501
        self._key = None
        self._filesystem = None
        self._volume = None
        self.discriminator = None
        if key is not None:
            self.key = key
        if filesystem is not None:
            self.filesystem = filesystem
        if volume is not None:
            self.volume = volume

    @property
    def key(self):
        """Gets the key of this DeviceNameDoformatBody.  # noqa: E501


        :return: The key of this DeviceNameDoformatBody.  # noqa: E501
        :rtype: FormatKey
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this DeviceNameDoformatBody.


        :param key: The key of this DeviceNameDoformatBody.  # noqa: E501
        :type: FormatKey
        """

        self._key = key

    @property
    def filesystem(self):
        """Gets the filesystem of this DeviceNameDoformatBody.  # noqa: E501

        Filesystem to format to (supportedFilesystems returns list of supported fileSystems)  # noqa: E501

        :return: The filesystem of this DeviceNameDoformatBody.  # noqa: E501
        :rtype: str
        """
        return self._filesystem

    @filesystem.setter
    def filesystem(self, filesystem):
        """Sets the filesystem of this DeviceNameDoformatBody.

        Filesystem to format to (supportedFilesystems returns list of supported fileSystems)  # noqa: E501

        :param filesystem: The filesystem of this DeviceNameDoformatBody.  # noqa: E501
        :type: str
        """

        self._filesystem = filesystem

    @property
    def volume(self):
        """Gets the volume of this DeviceNameDoformatBody.  # noqa: E501

        Volume name to set for the disk after format  # noqa: E501

        :return: The volume of this DeviceNameDoformatBody.  # noqa: E501
        :rtype: str
        """
        return self._volume

    @volume.setter
    def volume(self, volume):
        """Sets the volume of this DeviceNameDoformatBody.

        Volume name to set for the disk after format  # noqa: E501

        :param volume: The volume of this DeviceNameDoformatBody.  # noqa: E501
        :type: str
        """

        self._volume = volume

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeviceNameDoformatBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeviceNameDoformatBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
