# coding: utf-8

"""
    Audio Control API

    API For controlling audio on Blackmagic Design Cameras  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DescriptionCapabilitiesPadding(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'available': 'bool',
        'forced': 'bool',
        'value': 'float'
    }

    attribute_map = {
        'available': 'available',
        'forced': 'forced',
        'value': 'value'
    }

    def __init__(self, available=None, forced=None, value=None):  # noqa: E501
        """DescriptionCapabilitiesPadding - a model defined in Swagger"""  # noqa: E501
        self._available = None
        self._forced = None
        self._value = None
        self.discriminator = None
        if available is not None:
            self.available = available
        if forced is not None:
            self.forced = forced
        if value is not None:
            self.value = value

    @property
    def available(self):
        """Gets the available of this DescriptionCapabilitiesPadding.  # noqa: E501

        Input supports setting of padding  # noqa: E501

        :return: The available of this DescriptionCapabilitiesPadding.  # noqa: E501
        :rtype: bool
        """
        return self._available

    @available.setter
    def available(self, available):
        """Sets the available of this DescriptionCapabilitiesPadding.

        Input supports setting of padding  # noqa: E501

        :param available: The available of this DescriptionCapabilitiesPadding.  # noqa: E501
        :type: bool
        """

        self._available = available

    @property
    def forced(self):
        """Gets the forced of this DescriptionCapabilitiesPadding.  # noqa: E501

        Padding is forced to be set for the input  # noqa: E501

        :return: The forced of this DescriptionCapabilitiesPadding.  # noqa: E501
        :rtype: bool
        """
        return self._forced

    @forced.setter
    def forced(self, forced):
        """Sets the forced of this DescriptionCapabilitiesPadding.

        Padding is forced to be set for the input  # noqa: E501

        :param forced: The forced of this DescriptionCapabilitiesPadding.  # noqa: E501
        :type: bool
        """

        self._forced = forced

    @property
    def value(self):
        """Gets the value of this DescriptionCapabilitiesPadding.  # noqa: E501

        Value of the padding in dB  # noqa: E501

        :return: The value of this DescriptionCapabilitiesPadding.  # noqa: E501
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this DescriptionCapabilitiesPadding.

        Value of the padding in dB  # noqa: E501

        :param value: The value of this DescriptionCapabilitiesPadding.  # noqa: E501
        :type: float
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DescriptionCapabilitiesPadding, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DescriptionCapabilitiesPadding):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
