# coding: utf-8

"""
    Audio Control API

    API For controlling audio on Blackmagic Design Cameras  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Description(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'gain_range': 'DescriptionGainRange',
        'capabilities': 'DescriptionCapabilities'
    }

    attribute_map = {
        'gain_range': 'gainRange',
        'capabilities': 'capabilities'
    }

    def __init__(self, gain_range=None, capabilities=None):  # noqa: E501
        """Description - a model defined in Swagger"""  # noqa: E501
        self._gain_range = None
        self._capabilities = None
        self.discriminator = None
        if gain_range is not None:
            self.gain_range = gain_range
        if capabilities is not None:
            self.capabilities = capabilities

    @property
    def gain_range(self):
        """Gets the gain_range of this Description.  # noqa: E501


        :return: The gain_range of this Description.  # noqa: E501
        :rtype: DescriptionGainRange
        """
        return self._gain_range

    @gain_range.setter
    def gain_range(self, gain_range):
        """Sets the gain_range of this Description.


        :param gain_range: The gain_range of this Description.  # noqa: E501
        :type: DescriptionGainRange
        """

        self._gain_range = gain_range

    @property
    def capabilities(self):
        """Gets the capabilities of this Description.  # noqa: E501


        :return: The capabilities of this Description.  # noqa: E501
        :rtype: DescriptionCapabilities
        """
        return self._capabilities

    @capabilities.setter
    def capabilities(self, capabilities):
        """Sets the capabilities of this Description.


        :param capabilities: The capabilities of this Description.  # noqa: E501
        :type: DescriptionCapabilities
        """

        self._capabilities = capabilities

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Description, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Description):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
