# coding: utf-8

"""
    Audio Control API

    API For controlling audio on Blackmagic Design Cameras  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Input(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'input': 'str'
    }

    attribute_map = {
        'input': 'input'
    }

    def __init__(self, input=None):  # noqa: E501
        """Input - a model defined in Swagger"""  # noqa: E501
        self._input = None
        self.discriminator = None
        if input is not None:
            self.input = input

    @property
    def input(self):
        """Gets the input of this Input.  # noqa: E501


        :return: The input of this Input.  # noqa: E501
        :rtype: str
        """
        return self._input

    @input.setter
    def input(self, input):
        """Sets the input of this Input.


        :param input: The input of this Input.  # noqa: E501
        :type: str
        """
        allowed_values = ["None", "Camera - Left", "Camera - Right", "Camera - Mono", "XLR1 - Mic", "XLR1 - Line", "XLR2 - Mic", "XLR2 - Line", "3.5mm Left - Line", "3.5mm Left - Mic", "3.5mm Right - Line", "3.5mm Right - Mic", "3.5mm Mono - Line", "3.5mm Mono - Mic"]  # noqa: E501
        if input not in allowed_values:
            raise ValueError(
                "Invalid value for `input` ({0}), must be one of {1}"  # noqa: E501
                .format(input, allowed_values)
            )

        self._input = input

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Input, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Input):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
