# coding: utf-8

"""
    Audio Control API

    API For controlling audio on Blackmagic Design Cameras  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LowCutFilter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'low_cut_filter': 'bool'
    }

    attribute_map = {
        'low_cut_filter': 'lowCutFilter'
    }

    def __init__(self, low_cut_filter=None):  # noqa: E501
        """LowCutFilter - a model defined in Swagger"""  # noqa: E501
        self._low_cut_filter = None
        self.discriminator = None
        if low_cut_filter is not None:
            self.low_cut_filter = low_cut_filter

    @property
    def low_cut_filter(self):
        """Gets the low_cut_filter of this LowCutFilter.  # noqa: E501


        :return: The low_cut_filter of this LowCutFilter.  # noqa: E501
        :rtype: bool
        """
        return self._low_cut_filter

    @low_cut_filter.setter
    def low_cut_filter(self, low_cut_filter):
        """Sets the low_cut_filter of this LowCutFilter.


        :param low_cut_filter: The low_cut_filter of this LowCutFilter.  # noqa: E501
        :type: bool
        """

        self._low_cut_filter = low_cut_filter

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LowCutFilter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LowCutFilter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
