# coding: utf-8

"""
    Video Control API

    API For controlling the video on Blackmagic Design products  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AutoExposureMode(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mode': 'str',
        'type': 'str'
    }

    attribute_map = {
        'mode': 'mode',
        'type': 'type'
    }

    def __init__(self, mode=None, type=None):  # noqa: E501
        """AutoExposureMode - a model defined in Swagger"""  # noqa: E501
        self._mode = None
        self._type = None
        self.discriminator = None
        if mode is not None:
            self.mode = mode
        if type is not None:
            self.type = type

    @property
    def mode(self):
        """Gets the mode of this AutoExposureMode.  # noqa: E501


        :return: The mode of this AutoExposureMode.  # noqa: E501
        :rtype: str
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this AutoExposureMode.


        :param mode: The mode of this AutoExposureMode.  # noqa: E501
        :type: str
        """
        allowed_values = ["Off", "Continuous", "OneShot"]  # noqa: E501
        if mode not in allowed_values:
            raise ValueError(
                "Invalid value for `mode` ({0}), must be one of {1}"  # noqa: E501
                .format(mode, allowed_values)
            )

        self._mode = mode

    @property
    def type(self):
        """Gets the type of this AutoExposureMode.  # noqa: E501


        :return: The type of this AutoExposureMode.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this AutoExposureMode.


        :param type: The type of this AutoExposureMode.  # noqa: E501
        :type: str
        """
        allowed_values = ["", "Iris", "Shutter", "Iris,Shutter", "Shutter,Iris"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AutoExposureMode, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AutoExposureMode):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
