# coding: utf-8

"""
    Video Control API

    API For controlling the video on Blackmagic Design products  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NdFilterDisplayModeBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'display_mode': 'NdFilterDisplayMode'
    }

    attribute_map = {
        'display_mode': 'displayMode'
    }

    def __init__(self, display_mode=None):  # noqa: E501
        """NdFilterDisplayModeBody - a model defined in Swagger"""  # noqa: E501
        self._display_mode = None
        self.discriminator = None
        if display_mode is not None:
            self.display_mode = display_mode

    @property
    def display_mode(self):
        """Gets the display_mode of this NdFilterDisplayModeBody.  # noqa: E501


        :return: The display_mode of this NdFilterDisplayModeBody.  # noqa: E501
        :rtype: NdFilterDisplayMode
        """
        return self._display_mode

    @display_mode.setter
    def display_mode(self, display_mode):
        """Sets the display_mode of this NdFilterDisplayModeBody.


        :param display_mode: The display_mode of this NdFilterDisplayModeBody.  # noqa: E501
        :type: NdFilterDisplayMode
        """

        self._display_mode = display_mode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NdFilterDisplayModeBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NdFilterDisplayModeBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
