# coding: utf-8

# flake8: noqa
"""
    Preset Control API

    API For controlling the presets on Blackmagic Design products  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from PresetControl.models.active_preset import ActivePreset
from PresetControl.models.post_preset_response import PostPresetResponse
from PresetControl.models.preset_list import PresetList
