# coding: utf-8

"""
    Preset Control API

    API For controlling the presets on Blackmagic Design products  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from PresetControl.api_client import ApiClient


class DefaultApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def presets_active_get(self, **kwargs):  # noqa: E501
        """Get the list of the presets on the camera  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.presets_active_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: ActivePreset
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.presets_active_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.presets_active_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def presets_active_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get the list of the presets on the camera  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.presets_active_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: ActivePreset
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method presets_active_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/presets/active', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ActivePreset',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def presets_active_put(self, **kwargs):  # noqa: E501
        """Set the active preset on the camera  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.presets_active_put(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ActivePreset body:
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.presets_active_put_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.presets_active_put_with_http_info(**kwargs)  # noqa: E501
            return data

    def presets_active_put_with_http_info(self, **kwargs):  # noqa: E501
        """Set the active preset on the camera  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.presets_active_put_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ActivePreset body:
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method presets_active_put" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/presets/active', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def presets_get(self, **kwargs):  # noqa: E501
        """Get the list of the presets on the camera  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.presets_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: PresetList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.presets_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.presets_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def presets_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get the list of the presets on the camera  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.presets_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: PresetList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method presets_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/presets', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PresetList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def presets_post(self, **kwargs):  # noqa: E501
        """Send a preset file to the camera  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.presets_post(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Object body:
        :return: PostPresetResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.presets_post_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.presets_post_with_http_info(**kwargs)  # noqa: E501
            return data

    def presets_post_with_http_info(self, **kwargs):  # noqa: E501
        """Send a preset file to the camera  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.presets_post_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Object body:
        :return: PostPresetResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method presets_post" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/octet-stream'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/presets', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PostPresetResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def presets_preset_name_delete(self, preset_name, **kwargs):  # noqa: E501
        """Delete a preset from a camera if exists  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.presets_preset_name_delete(preset_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str preset_name: name of the preset file (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.presets_preset_name_delete_with_http_info(preset_name, **kwargs)  # noqa: E501
        else:
            (data) = self.presets_preset_name_delete_with_http_info(preset_name, **kwargs)  # noqa: E501
            return data

    def presets_preset_name_delete_with_http_info(self, preset_name, **kwargs):  # noqa: E501
        """Delete a preset from a camera if exists  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.presets_preset_name_delete_with_http_info(preset_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str preset_name: name of the preset file (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['preset_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method presets_preset_name_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'preset_name' is set
        if ('preset_name' not in params or
                params['preset_name'] is None):
            raise ValueError("Missing the required parameter `preset_name` when calling `presets_preset_name_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'preset_name' in params:
            path_params['presetName'] = params['preset_name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/presets/{presetName}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def presets_preset_name_get(self, preset_name, **kwargs):  # noqa: E501
        """Download the preset file  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.presets_preset_name_get(preset_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str preset_name: name of the preset file (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.presets_preset_name_get_with_http_info(preset_name, **kwargs)  # noqa: E501
        else:
            (data) = self.presets_preset_name_get_with_http_info(preset_name, **kwargs)  # noqa: E501
            return data

    def presets_preset_name_get_with_http_info(self, preset_name, **kwargs):  # noqa: E501
        """Download the preset file  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.presets_preset_name_get_with_http_info(preset_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str preset_name: name of the preset file (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['preset_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method presets_preset_name_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'preset_name' is set
        if ('preset_name' not in params or
                params['preset_name'] is None):
            raise ValueError("Missing the required parameter `preset_name` when calling `presets_preset_name_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'preset_name' in params:
            path_params['presetName'] = params['preset_name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/octet-stream'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/presets/{presetName}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def presets_preset_name_put(self, preset_name, **kwargs):  # noqa: E501
        """Update a preset on the camera if it exists, if not create a preset and save current state with the presetName  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.presets_preset_name_put(preset_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str preset_name: name of the preset file (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.presets_preset_name_put_with_http_info(preset_name, **kwargs)  # noqa: E501
        else:
            (data) = self.presets_preset_name_put_with_http_info(preset_name, **kwargs)  # noqa: E501
            return data

    def presets_preset_name_put_with_http_info(self, preset_name, **kwargs):  # noqa: E501
        """Update a preset on the camera if it exists, if not create a preset and save current state with the presetName  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.presets_preset_name_put_with_http_info(preset_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str preset_name: name of the preset file (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['preset_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method presets_preset_name_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'preset_name' is set
        if ('preset_name' not in params or
                params['preset_name'] is None):
            raise ValueError("Missing the required parameter `preset_name` when calling `presets_preset_name_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'preset_name' in params:
            path_params['presetName'] = params['preset_name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/presets/{presetName}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
